# Generated by Django 4.1.3 on 2022-12-14 13:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diap', '0002_alter_persontypesocialnetworkchoices_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='data_when_die',
        ),
        migrations.RemoveField(
            model_name='person',
            name='place_where_die',
        ),
        migrations.AddField(
            model_name='person',
            name='data_when_accident',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата інциденту'),
        ),
        migrations.AddField(
            model_name='person',
            name='job_title',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Посада'),
        ),
        migrations.AddField(
            model_name='person',
            name='place_where_accident',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Місце інцидету'),
        ),
        migrations.AddField(
            model_name='person',
            name='type_of_army',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Рід військ'),
        ),
        migrations.AddField(
            model_name='personsocialnetwork',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Час створення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personsocialnetwork',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Час останьої зміни'),
        ),
        migrations.AddField(
            model_name='persontext',
            name='text_url',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Посилання на текст'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='Дата народження'),
        ),
        migrations.AlterField(
            model_name='person',
            name='citizenship',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Громадянство'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='person',
            name='individual_identification_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Індитифікаційний код'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Побатькові'),
        ),
        migrations.AlterField(
            model_name='person',
            name='military_from',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Місце знаходження військової частини'),
        ),
        migrations.AlterField(
            model_name='person',
            name='military_unit',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Військова частина'),
        ),
        migrations.AlterField(
            model_name='person',
            name='passport',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Паспорт'),
        ),
        migrations.AlterField(
            model_name='person',
            name='place_of_birthday',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Місце народження'),
        ),
        migrations.AlterField(
            model_name='person',
            name='place_of_living',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Місце проживання'),
        ),
        migrations.AlterField(
            model_name='person',
            name='post_status',
            field=models.CharField(choices=[('DELETED', 'Deleted'), ('PUBLISHED', 'Published'), ('PROCESSING', 'Processing')], default='PROCESSING', max_length=32, verbose_name='Статус поста'),
        ),
        migrations.AlterField(
            model_name='person',
            name='range',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Військове звання'),
        ),
        migrations.AlterField(
            model_name='person',
            name='status_person',
            field=models.CharField(choices=[('ALIVE', 'Alive'), ('CAPTIVITY', 'Captivity'), ('DIE', 'Die'), ('MISSING_PERSON', 'Missing person')], default='DIE', max_length=32, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='person',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Час створення'),
        ),
        migrations.AlterField(
            model_name='person',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Час останьої зміни'),
        ),
        migrations.AlterField(
            model_name='personplacewherehewas',
            name='place',
            field=models.CharField(max_length=128, verbose_name='Місця дислокації'),
        ),
        migrations.AlterField(
            model_name='personplacewherehewas',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Час створення'),
        ),
        migrations.AlterField(
            model_name='personplacewherehewas',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Час останьої зміни'),
        ),
        migrations.AlterField(
            model_name='personsocialnetwork',
            name='profile',
            field=models.CharField(max_length=128, verbose_name='Посилання на профіль'),
        ),
        migrations.AlterField(
            model_name='personsocialnetwork',
            name='profile_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Логін профілю'),
        ),
        migrations.AlterField(
            model_name='personsocialnetwork',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diap.persontypesocialnetworkchoices', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='persontext',
            name='text',
            field=models.CharField(max_length=8192, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='persontext',
            name='text_from',
            field=models.CharField(max_length=128, verbose_name='Звідки текст (Домен)'),
        ),
        migrations.AlterField(
            model_name='persontext',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Час створення'),
        ),
        migrations.AlterField(
            model_name='persontext',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Час останьої зміни'),
        ),
    ]
